### PR TITLE
Rewards API

### PR DESCRIPTION
**Pull request by gowthamsundaresan**
### Intro
- `AVSRewardsSubmissionCreated` is emmitted when an AVS decided to send rewards to its stakers/operators
- `RewardsSubmissionForAllCreated` is emmitted when EigenLayer or any other whitelisted entity decides to send rewards to  stakers
- There will soon be a new event `RewardsSubmissionForAllEarnersCreated` which would be emitted when EigenLayer or any other whitelisted entity decides to send send rewards to operators AND stakers
- A given rewards submission describes
        a. The token it is rewarding
        b. The amount of tokens
        c. The list of strategies it is rewarding
        d. The relative weights of each strategy, according to which the amount of tokens will be split

### Data Pipeline
- Capture all logs of `AVSRewardsSubmissionCreated` & seed it to data table `AvsRewardSubmissions`
- Capture all logs of `RewardsSubmissionForAllCreated` & seed it to data table `GlobalRewardSubmissions`
- Note: For a given rewards submission, the calculation of splitting `amount` of token rewards across strategies is done in the data seeder

### API Routes
1. All rewards submitted by a given AVS
```
GET /avs/:address

{
    "avsAddress": "0x870679e138bcdf293b7ff14dd44b70fc97e12fc0",
    "submissions": [
        {
            "rewardsSubmissionHash": "0x990a5bee0c1524df556c07e41150bdb6992b93e7e666feabf9e66af702766b03",
            "startTimestamp": 1725494400,
            "duration": 2419200,
            "totalAmount": "5000000000000000000",
            "rewards": [
                {
                    "tokenAddress": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
                    "strategies": [
                        {
                            "strategyAddress": "0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6",
                            "multiplier": "1068966896363604679",
                            "amount": "387065842390268308.07"
                        },
                        {
                            "strategyAddress": "0x13760f50a9d7377e4f20cb8cf9e4c26586c658ff",
                            "multiplier": "1167295905003755853",
                            "amount": "422670126012306872.02"
                        },
                        {
                            "strategyAddress": "0x1bee69b7dfffa4e2d53c2a2df135c388ad25dcd2",
                            "multiplier": "1114663583060673944",
                            "amount": "403612310378205803.02"
                        },
                        {
                            "strategyAddress": "0x298afb19a105d59e74658c4c334ff360bade6dd2",
                            "multiplier": "1042115533310839238",
                            "amount": "377343141439751349.95"
                        },
                        {
                            "strategyAddress": "0x54945180db7943c0ed0fee7edab2bd24620256bc",
                            "multiplier": "1080022650414740066",
                            "amount": "391069057802849945.4"
                        },
                        {
                            "strategyAddress": "0x57ba429517c3473b6d34ca9acd56c0e735b94c02",
                            "multiplier": "1025010945212823010",
                            "amount": "371149683229381065.39"
                        },
                        {
                            "strategyAddress": "0x7ca911e83dabf90c90dd3de5411a10f1a6112184",
                            "multiplier": "1047995874333000000",
                            "amount": "379472374027801960.47"
                        },
                        {
                            "strategyAddress": "0x8ca7a5d6f3acd3a7a8bc468a8cd0fb14b6bd28b6",
                            "multiplier": "1096547124777235201",
                            "amount": "397052460666805405.09"
                        },
                        {
                            "strategyAddress": "0x93c4b944d05dfe6df7645a86cd2206016c51564d",
                            "multiplier": "1043185676128837999",
                            "amount": "377730633075587463.1"
                        },
                        {
                            "strategyAddress": "0x9d7ed45ee2e8fc5482fa2428f15c971e6369011d",
                            "multiplier": "1038703328428972081",
                            "amount": "376107604622380300.03"
                        },
                        {
                            "strategyAddress": "0xa4c637e0f704745d182e4d38cab7e7485321d059",
                            "multiplier": "1027044953080930383",
                            "amount": "371886184024284651.4"
                        },
                        {
                            "strategyAddress": "0xae60d8180437b5c34bb956822ac2710972584473",
                            "multiplier": "1057040013302350278",
                            "amount": "382747196925288093.13"
                        },
                        {
                            "strategyAddress": "0xbeac0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeebeac0",
                            "multiplier": "1000000000000000000",
                            "amount": "362093385405088782.94"
                        }
                    ]
                }
            ]
        },
        {
            "rewardsSubmissionHash": "0xf68e54d2172bc9b7a363a5cc4ba18a786b07ccb7f87902e37d4662ecfa5bb838",
            "startTimestamp": 1725494400,
            "duration": 2419200,
            "totalAmount": "5000000000000000000",
            "rewards": [
                {
                    "tokenAddress": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
                    "strategies": [
                        {
                            "strategyAddress": "0xacb55c530acdb2849e6d4f36992cd8c9d50ed8f7",
                            "multiplier": "1000000000000000000",
                            "amount": "5000000000000000000"
                        }
                    ]
                }
            ]
        }
    ],
    "totalRewards": 10000000000000000000,
    "totalSubmissions": 2
}
```

2. All tokens in which an AVS gives rewards (and their associated strategies)
```
GET /avs/:address/tokens

{
    "avsAddress": "0x1de75eaab2df55d467494a172652579e6fa4540e",
    "tokens": [
        {
            "tokenAddress": "0xba50933c268f567bdc86e1ac131be072c6b0b71a",
            "strategies": [
                "0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6",
                "0x13760f50a9d7377e4f20cb8cf9e4c26586c658ff",
                "0x1bee69b7dfffa4e2d53c2a2df135c388ad25dcd2",
                "0x298afb19a105d59e74658c4c334ff360bade6dd2",
                "0x54945180db7943c0ed0fee7edab2bd24620256bc",
                "0x57ba429517c3473b6d34ca9acd56c0e735b94c02",
                "0x7ca911e83dabf90c90dd3de5411a10f1a6112184",
                "0x8ca7a5d6f3acd3a7a8bc468a8cd0fb14b6bd28b6",
                "0x93c4b944d05dfe6df7645a86cd2206016c51564d",
                "0x9d7ed45ee2e8fc5482fa2428f15c971e6369011d",
                "0xa4c637e0f704745d182e4d38cab7e7485321d059",
                "0xae60d8180437b5c34bb956822ac2710972584473",
                "0xbeac0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeebeac0",
                "0xacb55c530acdb2849e6d4f36992cd8c9d50ed8f7"
            ]
        }
    ],
    "total": 1
}
```

3. All strategies that an AVS rewards (and their associated tokens)
```
GET /avs/:address/strategies

{
    "avsAddress": "0x1de75eaab2df55d467494a172652579e6fa4540e",
    "strategies": [
        {
            "strategyAddress": "0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0x13760f50a9d7377e4f20cb8cf9e4c26586c658ff",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0x1bee69b7dfffa4e2d53c2a2df135c388ad25dcd2",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0x298afb19a105d59e74658c4c334ff360bade6dd2",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0x54945180db7943c0ed0fee7edab2bd24620256bc",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0x57ba429517c3473b6d34ca9acd56c0e735b94c02",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0x7ca911e83dabf90c90dd3de5411a10f1a6112184",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0x8ca7a5d6f3acd3a7a8bc468a8cd0fb14b6bd28b6",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0x93c4b944d05dfe6df7645a86cd2206016c51564d",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0x9d7ed45ee2e8fc5482fa2428f15c971e6369011d",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0xa4c637e0f704745d182e4d38cab7e7485321d059",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0xae60d8180437b5c34bb956822ac2710972584473",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0xbeac0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeebeac0",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        },
        {
            "strategyAddress": "0xacb55c530acdb2849e6d4f36992cd8c9d50ed8f7",
            "tokens": [
                "0xba50933c268f567bdc86e1ac131be072c6b0b71a"
            ]
        }
    ],
    "total": 14
}
```

4. Get strategy-wise, avg & aggregate APY for a given AVS
```
GET /avs/:address/apy

{
    "avsAddress": "0x870679e138bcdf293b7ff14dd44b70fc97e12fc0",
    "strategies": [
        {
            "strategyAddress": "0xbeac0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeebeac0",
            "apy": 0.00018371028095009233
        },
        {
            "strategyAddress": "0x93c4b944d05dfe6df7645a86cd2206016c51564d",
            "apy": 0.0017673185209461312
        },
        {
            "strategyAddress": "0x1bee69b7dfffa4e2d53c2a2df135c388ad25dcd2",
            "apy": 0.018826454572898648
        },
        {
            "strategyAddress": "0x54945180db7943c0ed0fee7edab2bd24620256bc",
            "apy": 0.05149515942683051
        },
        {
            "strategyAddress": "0x9d7ed45ee2e8fc5482fa2428f15c971e6369011d",
            "apy": 0.006528548488477086
        },
        {
            "strategyAddress": "0x13760f50a9d7377e4f20cb8cf9e4c26586c658ff",
            "apy": 0.7955521088727968
        },
        {
            "strategyAddress": "0xa4c637e0f704745d182e4d38cab7e7485321d059",
            "apy": 0.05797291584533907
        },
        {
            "strategyAddress": "0x57ba429517c3473b6d34ca9acd56c0e735b94c02",
            "apy": 0.02834154741919031
        },
        {
            "strategyAddress": "0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6",
            "apy": 0.00948648695996194
        },
        {
            "strategyAddress": "0x7ca911e83dabf90c90dd3de5411a10f1a6112184",
            "apy": 0.015774640050063352
        },
        {
            "strategyAddress": "0x8ca7a5d6f3acd3a7a8bc468a8cd0fb14b6bd28b6",
            "apy": 0.061609583095105
        },
        {
            "strategyAddress": "0xae60d8180437b5c34bb956822ac2710972584473",
            "apy": 0.05088654566436827
        },
        {
            "strategyAddress": "0x298afb19a105d59e74658c4c334ff360bade6dd2",
            "apy": 0.018377251750055335
        },
        {
            "strategyAddress": "0xacb55c530acdb2849e6d4f36992cd8c9d50ed8f7",
            "apy": 0
        },
        {
            "strategyAddress": "0x6075546538c3efbd607ea6afc24149fccfb2edf4",
            "apy": 0
        }
    ],
    "aggregate": 1.1168022709469825,
    "average": 0.07445348472979883
}
```

5. Get strategy-wise, AVS-wise, avg & aggregate APY for a given Operator
```
GET /operators/:address/apy

{
    "operatorAddress": "0xdbed88d83176316fc46797b43adee927dc2ff2f5",
    "avs": [
        {
            "avsAddress": "0x1de75eaab2df55d467494a172652579e6fa4540e",
            "apy": 0.10582610668756359
        },
        {
            "avsAddress": "0x870679e138bcdf293b7ff14dd44b70fc97e12fc0",
            "apy": 1.11438474692528
        }
    ],
    "strategies": [
        {
            "strategyAddress": "0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6",
            "apy": 0.0007383362067407655
        },
        {
            "strategyAddress": "0x13760f50a9d7377e4f20cb8cf9e4c26586c658ff",
            "apy": 0.06955045499846894
        },
        {
            "strategyAddress": "0x1bee69b7dfffa4e2d53c2a2df135c388ad25dcd2",
            "apy": 0.0018012208655786444
        },
        {
            "strategyAddress": "0x298afb19a105d59e74658c4c334ff360bade6dd2",
            "apy": 0.0018880449016215324
        },
        {
            "strategyAddress": "0x54945180db7943c0ed0fee7edab2bd24620256bc",
            "apy": 0.005077485341960875
        },
        {
            "strategyAddress": "0x57ba429517c3473b6d34ca9acd56c0e735b94c02",
            "apy": 0.0029889193653029537
        },
        {
            "strategyAddress": "0x7ca911e83dabf90c90dd3de5411a10f1a6112184",
            "apy": 0.0010986949419079838
        },
        {
            "strategyAddress": "0x8ca7a5d6f3acd3a7a8bc468a8cd0fb14b6bd28b6",
            "apy": 0.011652976835381775
        },
        {
            "strategyAddress": "0x93c4b944d05dfe6df7645a86cd2206016c51564d",
            "apy": 0.00008114511412472289
        },
        {
            "strategyAddress": "0x9d7ed45ee2e8fc5482fa2428f15c971e6369011d",
            "apy": 0.0008230943577807887
        },
        {
            "strategyAddress": "0xa4c637e0f704745d182e4d38cab7e7485321d059",
            "apy": 0.004461189673332808
        },
        {
            "strategyAddress": "0xae60d8180437b5c34bb956822ac2710972584473",
            "apy": 0.0036882694758630587
        },
        {
            "strategyAddress": "0xbeac0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeebeac0",
            "apy": 0.00197627460949875
        }
    ],
    "aggregate": 1.2202108536128435,
    "averageAvs": 0.6101054268064218,
    "averageStrategies": 0.0081404697451972
}
```

### CODE REVIEW

**Comment by gowthamsundaresan** [comment]
Updates:
- Fixed bug in calc of beacon chain rewards
- Fixed bug in calc of strategy apy for operators
- Include 10% operator fees in apy calculation & add `operatorEarnings` to response
- Change response keys, `aggregate` -> `aggregateApy` & `average` -> `averageApy`
- Remove data pipeline for global rewards

**Comment by uditdc** [comment]
Updates to the routes:

1. /avs/:address => include 'apy' as a flag
2. /operators/:address => include 'apy' as a flag
3. /avs/:address/rewards => include rewards submissions, aggregate and strategies + tokens
4. /operators/:address/rewards => include rewards strategies + tokens
5. /rewards/strategies => global rewards route that gives out which strategies reward which tokens

Thanks

**Comment by uditdc** [comment]
Some minor comments, 
1. we can change the flag on avs and operator routes from `apy=true` to `withRewards`
2. rename `avsAddress` to `address` on the [GET  /avs/:address/rewards] route
3. rename `operatorAddress` to `address` on the [GET /operators/:address/rewards]
4. rename `strategiesRewarded` to `rewardStrategies` on [GET  /avs/:address/rewards] and [GET /operators/:address/rewards] route

**Comment by gowthamsundaresan** [comment]
@uditdc Sounds good!

**Pull request merged**
